path = [
    "/home/jack/.cargo/bin",
    "/home/jack/.local/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/local/sbin",
    "/usr/bin/site_perl",
    "/usr/bin/vendor_perl",
    "/usr/bin/core_perl",
]

startup = [
    "alias ls = exa -l --group-directories-first",
    "alias dotfiles = git --git-dir ~/dotfiles --work-tree ~",
]

prompt = "starship prompt"
rm_always_trash = true
