[theme]
theme = "ctp-mocha"
[icons]
icons = "material-nf"

[[block]]
block = "net"

[[block]]
block = "cpu"
interval = 3
[[block]]
block = "memory"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S %z') "
timezone = ["Australia/Sydney", "UTC"]
interval = 1
